name: Production Deploy
on:
  push:
    branches: [master]
jobs:
  job_one:
    name: Production Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Undeploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: /var/rdss/scripts/uninstall.sh
          host: ${{ secrets.MISTERVEIGA }}
          username: ${{ secrets.MISTERVEIGA_USER }}
          privateKey: ${{ secrets.MISTERVEIGA_SSH }}
      - name: Deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: /var/rdss/scripts/install.sh
          host: ${{ secrets.MISTERVEIGA }}
          username: ${{ secrets.MISTERVEIGA_USER }}
          privateKey: ${{ secrets.MISTERVEIGA_SSH }}
            
